version: "3.8"

services:
  nginx:
    image: bybatkhuu/nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - ./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled
      # - ./configs/custom-mods:/etc/nginx/custom-mods
      # - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/storage/nginx/ssl:/etc/nginx/ssl
      - ./volumes/storage/nginx/www:/var/www
      - ./volumes/storage/nginx/logs:/var/log/nginx
      # - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
    network_mode: host
    # ports:
    #   - "80:80"
    #   - "443:443"
    tty: true
    # command: ["nginx -g 'daemon off;'"]
    # command: ["/bin/bash", "-i", "-c"]
