version: "3.8"

services:
  nginx:
    image: bybatkhuu/nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - ./volumes/storage/nginx/certs:/etc/letsencrypt
      - ./volumes/storage/nginx/www:/var/www/sites
      - ./volumes/storage/nginx/logs:/var/log/nginx
      - ./volumes/storage/nginx/configs/mod:/etc/nginx/mod
      - ./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled
      - ./volumes/storage/nginx/configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    tty: true
    command: ["chown -R www-data:www-group /var/log/nginx && service cron start && nginx -g 'daemon off;'"]
    # command: ["/bin/bash"]
