version: "3.8"

services:
  nginx:
    image: voiceprint/nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
    ports:
      - "80:${NGINX_PORT:-80}"
    tty: true
