version: "3.8"

services:
  nginx:
    image: voiceprint/nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
      - "./volumes/storage/nginx/ssl:/etc/nginx/ssl"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
    network_mode: host
    tty: true
