version: "3.8"

services:
  # certbot:
  #   image: voiceprint/certbot:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.certbot
  #   restart: unless-stopped
  #   environment:
  #     - TERM=${TERM:-xterm}
  #     - TZ=${TZ:-Asia/Seoul}
  #     - CERTBOT_EMAIL=${CERTBOT_EMAIL}
  #     - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
  #   env_file:
  #     - .env
  #   volumes:
  #     - "./volumes/storage/nginx/ssl:/etc/letsencrypt"
  #     - "./volumes/storage/nginx/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
  #     - "./volumes/storage/certbot/secrets:/root/.secrets/certbot"
  #     - "./volumes/storage/certbot/logs:/var/log/letsencrypt"
  #     - "./scripts/docker-entrypoint.certbot.sh:/usr/local/bin/docker-entrypoint.sh"
  #     - "./volumes/.vscode-server:/root/.vscode-server"
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 256M
  #   tty: true
  #   command: ["--new", "--staging"]
  #   command: ["--new", "--staging", "--dns=cloudflare"]
  #   command: ["/bin/bash"]

  nginx:
    # depends_on:
    #   - certbot
    # environment:
    #   - NGINX_BASIC_AUTH_USER=${NGINX_BASIC_AUTH_USER}
    #   - NGINX_BASIC_AUTH_PASS=${NGINX_BASIC_AUTH_PASS}
    # env_file:
    #   - .env
    volumes:
      - "./volumes/storage/nginx/www:/var/www"
      # - "./configs/conf.d:/etc/nginx/conf.d"
      # - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/conf.d/sites-enabled"
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./scripts/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    # network_mode: bridge
    # ports:
    #   - "80:80"
    #   - "443:443"
    # command: ["--https=lets"]
    # command: ["--https=self"]
    # command: ["/bin/bash"]
