version: "3.8"

services:
  nginx:
    # environment:
    #   - NGINX_BASIC_AUTH_USER=${NGINX_BASIC_AUTH_USER}
    #   - NGINX_BASIC_AUTH_PASS=${NGINX_BASIC_AUTH_PASS}
    # env_file:
    #   - .env
    volumes:
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
      - "./volumes/storage/nginx/www:/var/www"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
      - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled"
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./scripts/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    # network_mode: bridge
    # ports:
    #   - "80:80"
    #   - "443:443"
    # command: ["--https=lets"]
    # command: ["--https=self"]
    # command: ["/bin/bash"]
