version: "3.8"

# services:
#   certbot:
#     image: voiceprint/certbot:latest
#     build:
#       context: .
#       dockerfile: Dockerfile.certbot
#     restart: unless-stopped
#     environment:
#       - TERM=${TERM:-xterm}
#       - TZ=${TZ:-Asia/Seoul}
#       - CERTBOT_EMAIL=${CERTBOT_EMAIL}
#       - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
#     env_file:
#       - .env
#     volumes:
#       - "./volumes/storage/nginx/ssl:/etc/letsencrypt"
#       - "./volumes/storage/nginx/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
#       - "./volumes/storage/certbot/secrets:/root/.secrets/certbot"
#     deploy:
#       replicas: 0
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 256M
#     tty: true
#     command: ["--new"]
#     command: ["--new", "--dns=cloudflare"]
#     command: ["--dns=route53"]
#     command: ["/bin/bash"]

#   nginx:
#     depends_on:
#       - certbot
#     environment:
#       - NGINX_BASIC_AUTH_USER=${NGINX_BASIC_AUTH_USER}
#       - NGINX_BASIC_AUTH_PASS=${NGINX_BASIC_AUTH_PASS}
#     env_file:
#       - .env
#     volumes:
#       - "./volumes/storage/nginx/www:/var/www"
#       - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/conf.d/sites-enabled"
#     deploy:
#       replicas: 0
#       resources:
#         limits:
#           cpus: "1.0"
#           memory: 1G
#     network_mode: bridge
#     ports:
#       - "80:80"
#       - "443:443"
#     command: ["--https=lets"]
#     command: ["--https=self"]
#     command: ["/bin/bash"]
